<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function findPrix($product_id){

        $query=$this->getEntityManager()->createQuery(
            "SELECT a from  
              AppBundle:Produit a
               WHERE a.id=:produit_id")->setParameter('produit_id',$product_id);



        return $query->getResult();
    }
}
