<?php

namespace AppBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findPromotion($promotion_id){

        $query=$this->getEntityManager()->createQuery(
            "SELECT a from  
              AppBundle:Promotion a
               WHERE a.id=:promotion_id")->setParameter('promotion_id',$promotion_id);
        return $query->getResult();
    }

}
