bonlivraison_index:
    path:     /
    defaults: { _controller: "AppBundle:BonLivraison:index" }
    methods:  GET

bonlivraison_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:BonLivraison:show" }
    methods:  GET

bonlivraison_new:
    path:     /new
    defaults: { _controller: "AppBundle:BonLivraison:new" }
    methods:  [GET, POST]

bonlivraison_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:BonLivraison:edit" }
    methods:  [GET, POST]

bonlivraison_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:BonLivraison:delete" }
    methods:  DELETE
