quantitecommandee_index:
    path:     /
    defaults: { _controller: "AppBundle:QuantiteCommandee:index" }
    methods:  GET

quantitecommandee_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:QuantiteCommandee:show" }
    methods:  GET

quantitecommandee_new:
    path:     /new
    defaults: { _controller: "AppBundle:QuantiteCommandee:new" }
    methods:  [GET, POST]

quantitecommandee_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:QuantiteCommandee:edit" }
    methods:  [GET, POST]

quantitecommandee_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:QuantiteCommandee:delete" }
    methods:  DELETE
